package org.egov.wscalculation.djbmonthlybilling.service;

import java.util.Locale;
import java.util.UUID;

import org.egov.common.contract.request.RequestInfo;
import org.egov.wscalculation.djbmonthlybilling.model.WaterBillingCycle;
import org.egov.wscalculation.djbmonthlybilling.model.ZroVerification;
import org.egov.wscalculation.djbmonthlybilling.model.enums.BillingCycleStatus;
import org.egov.wscalculation.djbmonthlybilling.model.enums.ZroStatus;
import org.egov.wscalculation.djbmonthlybilling.repository.WaterBillingCycleDao;
import org.egov.wscalculation.djbmonthlybilling.repository.ZroVerificationDao;
import org.egov.wscalculation.web.models.Demand;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;

@Service
public class ZroVerificationService {

	private final WaterBillingCycleDao billingCycleDao;
	private final ZroVerificationDao zroVerificationDao;
	private final DJBMonthlyDemandService demandService;
	private final DJBShadowMeterBillingService djbShadowMeterBillingService;

	public ZroVerificationService(WaterBillingCycleDao billingCycleDao, ZroVerificationDao zroVerificationDao,
			DJBMonthlyDemandService demandService, DJBShadowMeterBillingService djbShadowMeterBillingService) {
		this.billingCycleDao = billingCycleDao;
		this.zroVerificationDao = zroVerificationDao;
		this.demandService = demandService;
		this.djbShadowMeterBillingService = djbShadowMeterBillingService;
	}

	public ZroVerificationResult update(RequestInfo requestInfo, String billingCycleId, String action, String remarks) {

		validateRequestInfo(requestInfo);

		String tenantId = requestInfo.getUserInfo().getTenantId();
		WaterBillingCycle cycle = billingCycleDao.findById(tenantId, billingCycleId);

		if (cycle == null) {
			throw new IllegalArgumentException("Billing cycle not found: " + billingCycleId);
		}

		if (!Boolean.TRUE.equals(cycle.getOnepointfivexflag())) {
			throw new IllegalStateException("ZRO action is only valid for a DJB 1.5x flagged billing cycle");
		}

		String normalizedAction = action == null ? "" : action.trim().toUpperCase(Locale.ROOT);

		if (!"APPROVE".equals(normalizedAction) && !"REJECT".equals(normalizedAction)) {
			throw new IllegalArgumentException("ZRO action must be APPROVE or REJECT");
		}

		String actor = requestInfo.getUserInfo().getUuid();
		ZroVerification verification = zroVerificationDao.findByBillingCycle(tenantId, billingCycleId);

		/*
		 * A valid ZRO action must operate on the verification generated by the billing
		 * cycle. If the record is unexpectedly missing, create a PENDING record from
		 * the immutable billing-cycle values so the action remains auditable and
		 * idempotent.
		 */
		if (verification == null) {
			verification = createPendingVerification(cycle, actor);
			if (zroVerificationDao.save(verification) != 1) {
				throw new IllegalStateException(
						"Failed to create ZRO verification for billing cycle " + billingCycleId);
			}
		}

		/*
		 * A terminal ZRO decision is immutable for a billing cycle. This prevents an
		 * APPROVE/REJECT request from accidentally reversing a previous decision.
		 */
		if (ZroStatus.APPROVED.equals(verification.getStatus())
				|| ZroStatus.REJECTED.equals(verification.getStatus())) {
			if (!isSameTerminalAction(normalizedAction, verification.getStatus())) {
				throw new IllegalStateException(
						"ZRO verification is already " + verification.getStatus() + " for billing cycle " + billingCycleId);
			}

			/*
			 * A terminal decision is immutable, but external billing work is retryable.
			 * If APPROVE/REJECT was persisted and the downstream demand/bill step failed,
			 * the same terminal request resumes that missing billing work instead of
			 * returning a false-success response.
			 */
			if (ZroStatus.APPROVED.equals(verification.getStatus())
					&& (!StringUtils.hasText(cycle.getDemandid()) || !StringUtils.hasText(cycle.getBillid()))) {
				djbShadowMeterBillingService.processCalculatedCycleAfterDecision(requestInfo, cycle);
				return result(cycle, verification, cycle.getDemandid(), cycle.getBillid(),
						StringUtils.hasText(cycle.getBillid())
								? "ZRO action already approved; billing completed on retry"
								: "ZRO action already approved; billing remains pending");
			}

			if (ZroStatus.REJECTED.equals(verification.getStatus())
					&& (!StringUtils.hasText(cycle.getDemandid()) || !StringUtils.hasText(cycle.getBillid()))) {
				DJBMonthlyDemandService.DemandResult retryResult = demandService
						.createRejectedOnePointFiveFallbackDemand(requestInfo, cycle);
				if (retryResult.isDemandCreated() && retryResult.getDemand() != null) {
					cycle.setDemandid(retryResult.getDemand().getId());
					cycle.setBillid(retryResult.getBillId());
					cycle.setStatus(StringUtils.hasText(retryResult.getBillId()) ? BillingCycleStatus.BILL_GENERATED
								: BillingCycleStatus.DEMAND_CREATED);
					cycle.setLastmodifiedby(actor);
					cycle.setLastmodifiedtime(System.currentTimeMillis());
					billingCycleDao.update(cycle);
				}
				return result(cycle, verification, cycle.getDemandid(), cycle.getBillid(),
						StringUtils.hasText(cycle.getBillid())
								? "ZRO action already rejected; fallback billing completed on retry"
								: "ZRO action already rejected; fallback billing remains pending");
			}

			return result(cycle, verification, cycle.getDemandid(), cycle.getBillid(), "ZRO action already applied");
		}

		/*
		 * A ZRO action is expected only while verification is PENDING. Treat any
		 * unexpected status as invalid rather than silently changing the workflow.
		 */
		if (!ZroStatus.PENDING.equals(verification.getStatus())) {
			throw new IllegalStateException(
					"ZRO verification is not in PENDING state for billing cycle " + billingCycleId);
		}

		long now = System.currentTimeMillis();
		String finalRemarks = StringUtils.hasText(remarks) ? remarks.trim() : verification.getRemarks();

		verification.setRemarks(finalRemarks);
		verification.setActionby(actor);
		verification.setActiondate(now);
		verification.setLastmodifiedby(actor);
		verification.setLastmodifiedtime(now);

		if ("REJECT".equals(normalizedAction)) {
			/*
			 * REJECT is terminal for the high-consumption approval decision, but it is
			 * NOT a terminal billing decision. As per the DJB 1.5x rule, once ZRO rejects
			 * the actual consumption, the cycle must fall back to average/provisional
			 * billing using historical consumption.
			 */
			if (StringUtils.hasText(cycle.getDemandid()) || StringUtils.hasText(cycle.getBillid())) {
				throw new IllegalStateException("Cannot reject ZRO verification because demand/bill already exists "
						+ "for billing cycle " + billingCycleId);
			}

			verification.setStatus(ZroStatus.REJECTED);

			cycle.setZrostatus(ZroStatus.REJECTED);
			cycle.setZroremarks(finalRemarks);
			cycle.setZroactionby(actor);
			cycle.setZroactiondate(now);
			cycle.setStatus(BillingCycleStatus.CALCULATED);
			cycle.setLastmodifiedby(actor);
			cycle.setLastmodifiedtime(now);

			if (zroVerificationDao.update(verification) != 1) {
				throw new IllegalStateException(
						"Failed to persist ZRO REJECTED status for billing cycle " + billingCycleId);
			}

			if (billingCycleDao.update(cycle) != 1) {
				throw new IllegalStateException(
						"Failed to persist billing-cycle ZRO REJECTED status for " + billingCycleId);
			}

			DJBMonthlyDemandService.DemandResult demandResult = demandService
					.createRejectedOnePointFiveFallbackDemand(requestInfo, cycle);

			if (!demandResult.isDemandCreated() || demandResult.getDemand() == null
					|| !StringUtils.hasText(demandResult.getDemand().getId())) {
				throw new IllegalStateException(
						"ZRO rejection did not create the fallback provisional demand for billing cycle " + billingCycleId);
			}

			Demand demand = demandResult.getDemand();
			cycle.setDemandid(demand.getId());
			cycle.setBillid(demandResult.getBillId());
			cycle.setStatus(StringUtils.hasText(demandResult.getBillId()) ? BillingCycleStatus.BILL_GENERATED
					: BillingCycleStatus.DEMAND_CREATED);
			cycle.setLastmodifiedby(actor);
			cycle.setLastmodifiedtime(System.currentTimeMillis());

			if (billingCycleDao.update(cycle) != 1) {
				throw new IllegalStateException(
						"Failed to persist fallback provisional demand/bill for billing cycle " + billingCycleId);
			}

			return result(cycle, verification, demand.getId(), demandResult.getBillId(),
					"DJB 1.5x consumption rejected by ZRO verification; fallback provisional bill generated");
		}

		/*
		 * APPROVE is the only path allowed to create the demand/bill for a ZRO flagged
		 * cycle.
		 */
		verification.setStatus(ZroStatus.APPROVED);

		cycle.setZrostatus(ZroStatus.APPROVED);
		cycle.setZroremarks(finalRemarks);
		cycle.setZroactionby(actor);
		cycle.setZroactiondate(now);
		cycle.setStatus(BillingCycleStatus.CALCULATED);
		cycle.setLastmodifiedby(actor);
		cycle.setLastmodifiedtime(now);

		if (zroVerificationDao.update(verification) != 1) {
			throw new IllegalStateException(
					"Failed to persist ZRO APPROVED status for billing cycle " + billingCycleId);
		}

		if (billingCycleDao.update(cycle) != 1) {
			throw new IllegalStateException(
					"Failed to persist billing-cycle ZRO APPROVED status for " + billingCycleId);
		}

		/*
		 * APPROVE is now the explicit hand-off into the normal ACTUAL billing path.
		 * If estimated cycles exist before this OK reading, the common correction
		 * orchestration consolidates the span before final bill generation.
		 */
		djbShadowMeterBillingService.processCalculatedCycleAfterDecision(requestInfo, cycle);

		return result(cycle, verification, cycle.getDemandid(), cycle.getBillid(),
				StringUtils.hasText(cycle.getBillid())
						? "DJB 1.5x consumption approved; demand and bill generated"
						: "DJB 1.5x consumption approved; billing remains pending");
	}

	private void validateRequestInfo(RequestInfo requestInfo) {
		if (requestInfo == null || requestInfo.getUserInfo() == null
				|| !StringUtils.hasText(requestInfo.getUserInfo().getUuid())) {
			throw new IllegalArgumentException("RequestInfo.userInfo.uuid is required for ZRO action");
		}

		if (!StringUtils.hasText(requestInfo.getUserInfo().getTenantId())) {
			throw new IllegalArgumentException("RequestInfo.userInfo.tenantId is required for ZRO action");
		}
	}

	private ZroVerification createPendingVerification(WaterBillingCycle cycle, String actor) {

		long now = System.currentTimeMillis();

		ZroVerification verification = new ZroVerification();
		verification.setId(UUID.randomUUID().toString());
		verification.setTenantid(cycle.getTenantid());
		verification.setBillingcycleid(cycle.getId());
		verification.setConnectionno(cycle.getConnectionno());
		verification.setConsumption(cycle.getActualconsumption());
		verification.setPreviousconsumption(cycle.getPreviousconsumption());
		verification.setDeviationfactor(cycle.getDeviationfactor());
		verification.setStatus(ZroStatus.PENDING);
		verification.setRemarks(cycle.getZroremarks());
		verification.setCreatedby(actor);
		verification.setCreatedtime(now);
		verification.setLastmodifiedby(actor);
		verification.setLastmodifiedtime(now);

		return verification;
	}

	private boolean isSameTerminalAction(String action, ZroStatus status) {

		return ("APPROVE".equals(action) && ZroStatus.APPROVED.equals(status))
				|| ("REJECT".equals(action) && ZroStatus.REJECTED.equals(status));
	}

	private ZroVerificationResult result(WaterBillingCycle cycle, ZroVerification verification, String demandId,
			String billId, String message) {

		return ZroVerificationResult.builder().verification(verification).billingCycle(cycle).demandId(demandId)
				.billId(billId).message(message).build();
	}

	@lombok.Data
	@lombok.Builder
	public static class ZroVerificationResult {
		private ZroVerification verification;
		private WaterBillingCycle billingCycle;
		private String demandId;
		private String billId;
		private String message;
	}
}
